apiVersion: extension/v1betav1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
    hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "presidenttimes.com"
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
