apiVersion: extension/v1betav1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
    - host:
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80